version: 2

jobs:
  build:
    machine:
      image: circleci/classic:201808-01

    steps:
      - checkout

      - run:
          name: create docker image
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
                make -f Makefile.co image
            else
                make -f Makefile.co image-branch
            fi

      - deploy:
          name: push docker image
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
                make -f Makefile.co push
            else
                make -f Makefile.co push-branch
            fi
